stages:
  - build
  - test
  - quality
  - reset

build:
  stage: build
  tags:
    - loketla-runner
  before_script:
    - docker version
    - docker-compose version
    - docker-compose down -v
  script:
    - docker-compose up --build -d
    - docker exec -t loketla-express chmod -R 0777 logs scripts
    - docker exec -t loketla-express npm run migrate:latest
    - docker exec -t loketla-express npm run seed:run

unit-integration-test:
  stage: test
  tags:
    - loketla-runner
  variables:
    GIT_CHECKOUT: "false"
  script:
    - docker exec -t loketla-express npm run test:jest:report
  after_script:
    - docker exec -t loketla-express chmod -R 0777 logs coverage
  artifacts:
    paths:
      - src/server/coverage/
    expire_in: 3 day

api-test:
  stage: test
  tags:
    - loketla-runner
  variables:
    GIT_CHECKOUT: "false"
  script:
    - docker exec -t loketla-express npm run test:newman:report
  artifacts:
    paths:
      - src/server/apis/test/report.html
    expire_in: 3 day

quality-control:
  stage: quality
  tags:
    - loketla-runner
  needs: ["build"]
  variables:
    GIT_CHECKOUT: "false"
  script:
    - docker exec -t loketla-express npm run lint

reset-container:
  stage: reset
  tags:
    - loketla-runner
  variables:
    GIT_CHECKOUT: "false"
  script:
    - docker exec -t loketla-express chmod -R 0777 logs coverage
    - docker system prune -f
    - docker-compose down -v
  dependencies:
    - api-test
    - unit-integration-test
