image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  tags:
    - loketla-runner
  script:
    - docker-compose down -v
    - docker-compose up --build -d
    - docker-compose run server npm run migrate:latest
    - docker-compose run server npm run seed:run
    - docker-compose run server npm run test:all:report
    - docker system prune -f
    - docker-compose down -v
  
