image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose up --build -d
    - docker exec -it loketla-express bash
    - npm run test:all:report
