image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - test
  - production

test:
  stage: test
  only:
    - pre-release
    - release
  script:
    - echo run tests in this section
