stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  tags:
    - loketla-runner
  script:
    - docker-compose down -v
    - docker-compose up --build -d
    - docker-compose exec -T loketla-express npm run migrate:latest
    - docker-compose exec -T loketla-express npm run seed:run
    - docker-compose exec -T loketla-express npm run test:all:report
    - docker system prune -f
    - docker-compose down -v
  artifacts:
    paths:
      - coverage/
      - apis/test/
  
