image:
  name: docker/compose:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build
  - test
  - quality

before_script:
  - docker version
  - docker-compose version
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

build-client:
  stage: build
  tags:
    - loketla-docker-runner
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_REF_NAME}-latest || true
    - docker build 
        --cache-from loketla/item-locating-system-client:${CI_COMMIT_REF_NAME}-latest 
        --tag loketla/item-locating-system-client:${CI_COMMIT_REF_NAME}-latest 
        --tag loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA} ./src/client
    - docker push loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker push loketla/item-locating-system-client:${CI_COMMIT_REF_NAME}-latest
build-server:
  stage: build
  tags:
    - loketla-docker-runner
  script:
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_REF_NAME}-latest || true
    - docker build 
        --cache-from loketla/item-locating-system-server:${CI_COMMIT_REF_NAME}-latest 
        --tag loketla/item-locating-system-server:${CI_COMMIT_REF_NAME}-latest 
        --tag loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA} ./src/server
    - docker push loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker push loketla/item-locating-system-server:${CI_COMMIT_REF_NAME}-latest
unit-integration-test:
  stage: test
  tags:
    - loketla-docker-runner
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker pull postgres:latest
    - docker-compose -f docker-compose-ci.yaml up -d
    - docker exec -t loketla-express npm run test:jest:report
api-test:
  stage: test
  tags:
    - loketla-docker-runner
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker pull postgres:latest
    - docker-compose -f docker-compose-ci.yaml up -d
    - docker exec -t loketla-express npm run test:newman:report
lint:
  stage: quality
  tags:
    - loketla-docker-runner
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker pull postgres:latest
    - docker-compose -f docker-compose-ci.yaml up -d
    - docker exec -t loketla-express npm run test:newman:report
