stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  tags:
    - loketla-runner
  script:
    - docker-compose down -v --privileged --user
    - docker-compose up --build -d --privileged --user
    - docker-compose exec -T server npm run migrate:latest --privileged --user
    - docker-compose exec -T server npm run seed:run --privileged --user
    - docker-compose exec -T server npm run test:all:report --privileged --user
    - docker system prune -f --privileged --user
    - docker-compose down -v --privileged --user
  after_script:
    - git gc && git clean -ffdx 
  artifacts:
    paths:
      - coverage/
      - apis/test/
  
