image:
  name: docker/compose:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always

stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

build-client:
  stage: build
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_REF_SLUG}-latest || true
    - docker build 
        --cache-from loketla/item-locating-system-client:${CI_COMMIT_REF_SLUG}-latest 
        --tag loketla/item-locating-system-client:${CI_COMMIT_REF_SLUG}-latest 
        --tag loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA} ./src/client
    - docker push loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker push loketla/item-locating-system-client:${CI_COMMIT_REF_SLUG}-latest
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
build-server:
  stage: build
  script:
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_REF_SLUG}-latest || true
    - docker build 
        --cache-from loketla/item-locating-system-server:${CI_COMMIT_REF_SLUG}-latest 
        --tag loketla/item-locating-system-server:${CI_COMMIT_REF_SLUG}-latest 
        --tag loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA} ./src/server
    - docker push loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker push loketla/item-locating-system-server:${CI_COMMIT_REF_SLUG}-latest
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
lint-unit-integration-test:
  stage: test
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker pull postgres:latest
    - docker-compose -f docker-compose-ci.yaml up -d
    - docker exec -t loketla-react npm run lint
    - docker exec -t loketla-express npm run lint
    - docker exec -t loketla-express npm run migrate:latest
    - docker exec -t loketla-express npm run seed:run
    - docker exec -t loketla-express npm run test:jest:report
  artifacts:
    paths:
      - src/server/coverage/
    expire_in: 3 day
    when: always
  allow_failure: true
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
api-test:
  stage: test
  script:
    - docker pull loketla/item-locating-system-client:${CI_COMMIT_SHORT_SHA}
    - docker pull loketla/item-locating-system-server:${CI_COMMIT_SHORT_SHA}
    - docker pull postgres:latest
    - docker-compose -f docker-compose-ci.yaml up -d
    - docker exec -t loketla-express chmod -R 0777 scripts
    - docker exec -t loketla-express npm run migrate:latest
    - docker exec -t loketla-express npm run seed:run
    - docker exec -t loketla-express npm run test:newman:report
  artifacts:
    paths:
      - src/server/apis/test/report.html
    expire_in: 4 day
    when: always
  allow_failure: true
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
