version: "3"
services:
  app:
    build: ./src/app
    container_name: loketla-app
    restart: always
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - ./src/app:/app/mobile
      - /app/mobile/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - server
  client:
    build: ./src/client
    container_name: loketla-react
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src/client:/app/client
      - /app/client/node_modules
    depends_on:
      - server
  server:
    build: ./src/server
    container_name: loketla-express
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      FORCE_COLOR: 3
    ports:
      - "8000:8000"
    volumes:
      - ./src/server:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pg-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pg-data:
