module.exports = {
  app_user: 'app_user',
  backoffice_user: 'backoffice_user',
  product: 'product',
  item: 'item',
  item_product: 'item_product',
  store: 'store',
  planning_cart: 'planning_cart',
  planning_cart_product: 'planning_cart_product',
  category: 'category',
  sub_category: 'sub_category',
  item_sub_category: 'item_sub_category',
  product_sub_category: 'product_sub_category',
  image: 'image',
  layer: 'layer',
  layout: 'layout',
  promotion: 'promotion',
  promotion_product: 'promotion_product',
  marketing_campaign: 'marketing_campaign',
};
